import{a as q,S as P,i as s}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const B="33787765-ed31b6debc6150c814f6bcf67",M="https://pixabay.com/api/";async function p(o,t=1){const a={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(M,{params:a})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:a,largeImageURL:i,tags:e,likes:r,views:c,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> <span>${r}</span></p>
        <p class="info-item"><b>Views</b> <span>${c}</span></p>
        <p class="info-item"><b>Comments</b> <span>${S}</span></p>
        <p class="info-item"><b>Downloads</b> <span>${v}</span></p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){f.innerHTML=""}function y(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function L(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const w=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",n=1,u=0;w.addEventListener("submit",x);O.addEventListener("click",E);async function x(o){if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!l){s.warning({message:"Please enter a search query!",position:"topRight"});return}n=1,$(),d(),y();try{const t=await p(l,n);if(u=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),u>n*15?L():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b(),w.reset()}}async function E(){n+=1,d(),y();try{const o=await p(l,n);g(o.hits),H(),n*15>=u?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{s.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b()}}function H(){const o=document.querySelector(".gallery-item");if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
